# Using SDKs
## Exploratory Data Analysis

In [1]:
import logging

# Configure the root logger
logging.basicConfig(
    level=logging.ERROR,  # 👈 this enables DEBUG level output
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s"
)

Import SDK and supporting libraries

In [6]:
import pandas as pd
from swcpy.swc_client import SWCClient
from swcpy.swc_config import SWCConfig

config = SWCConfig()
client = SWCClient(config)    

sdk_player_list = client.list_players()
player_df = pd.DataFrame([player.model_dump() for player in sdk_player_list])

display(player_df.shape)
display(player_df.head(3))
display(player_df.tail(3))
display(player_df.info())

SWC_API_BASE_URL in SWCConfig init: https://api.sportsworldcentral.com/

(100, 7)

,player_id,gsis_id,first_name,last_name,position,last_changed_date,performances
0,1001,00-0023459,Aaron,Rodgers,QB,2024-04-18,"[{'performance_id': 2501, 'player_id': 1001, '..."
1,1002,00-0023853,Matt,Prater,K,2024-04-18,"[{'performance_id': 2502, 'player_id': 1002, '..."
2,1003,00-0024243,Marcedes,Lewis,TE,2024-04-18,"[{'performance_id': 2503, 'player_id': 1003, '..."

,player_id,gsis_id,first_name,last_name,position,last_changed_date,performances
97,1098,00-0032398,Chris,Moore,WR,2024-04-18,"[{'performance_id': 2598, 'player_id': 1098, '..."
98,1099,00-0032434,Brandon,Allen,QB,2024-04-18,"[{'performance_id': 2599, 'player_id': 1099, '..."
99,1100,00-0032436,Jeff,Driskel,QB,2024-04-18,"[{'performance_id': 2600, 'player_id': 1100, '..."

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   player_id          100 non-null    int64
 1   gsis_id            100 non-null    object
 2   first_name         100 non-null    object
 3   last_name          100 non-null    object
 4   position           100 non-null    object
 5   last_changed_date  100 non-null    object
 6   performances       100 non-null    object
dtypes: int64(1), object(6)
memory usage: 5.6+ KB

None

In [5]:
player_df["performance_count"] = player_df["performances"].apply(len)
display(player_df["performance_count"].describe())

count    100.0
mean      17.0
std        0.0
min       17.0
25%       17.0
50%       17.0
75%       17.0
max       17.0
Name: performance_count, dtype: float64